version: '3.8'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbmongo:/data/db
      
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
  postgres:
    image: postgres
    volumes:
      - dbpostgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
volumes:
  dbmongo:
  dbpostgres: