# Generated by Django 5.0.3 on 2024-03-24 17:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('strategy_details', models.JSONField()),
                ('start_timestamp', models.DateTimeField(auto_now=True)),
                ('end_timestamp', models.DateTimeField()),
                ('member_quorum', models.FloatField(default=0.5)),
                ('vote_selected_option_count', models.JSONField()),
                ('vote_counts', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_selected_option', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
    ]
