# Generated by Django 5.0.3 on 2024-03-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='vote_selected_option_count',
            new_name='vote_selected_options_count',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='vote_counts',
            new_name='votes_counts',
        ),
    ]
