# Generated by Django 5.0.3 on 2024-03-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_rename_vote_selected_option_count_proposal_vote_selected_options_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='votes_counts',
            new_name='votes_count',
        ),
    ]
