# Generated by Django 5.0.3 on 2024-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_alter_proposal_end_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='end_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='start_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
