# Generated by Django 5.0.3 on 2024-03-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_alter_proposal_end_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
