# Generated by Django 5.0.3 on 2024-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_alter_proposal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='vote_selected_options_count',
            field=models.JSONField(default=dict),
        ),
    ]
