# Generated by Django 5.0.3 on 2024-04-03 16:37

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0008_spaceapptreenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolanaProgramIDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=40, null=True)),
                ('docs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, null=True, size=None)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), default=list, size=None)),
                ('state', models.JSONField(null=True)),
                ('accounts', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('constants', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
                ('metadata', models.JSONField(null=True)),
                ('docs_search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('program_search_vector', django.contrib.postgres.search.SearchVectorField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_solana_program', to='space.space')),
            ],
        ),
    ]
