# Generated by Django 5.0.3 on 2024-04-03 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappsuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solanaprogramidl',
            name='docs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
    ]
