# Generated by Django 5.0.3 on 2024-04-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappsuit', '0002_alter_solanaprogramidl_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solanaprogramidl',
            name='docs_search_vector',
        ),
        migrations.RemoveField(
            model_name='solanaprogramidl',
            name='program_search_vector',
        ),
        migrations.AddField(
            model_name='solanaprogramidl',
            name='docs_search_text',
            field=models.TextField(blank=True, default=str, null=True),
        ),
        migrations.AddField(
            model_name='solanaprogramidl',
            name='program_search_text',
            field=models.TextField(blank=True, default=str),
        ),
    ]
