# Generated by Django 5.0.3 on 2024-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappsuit', '0005_alter_solanaprogramidl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solanaprogramidl',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
