# Generated by Django 5.0.3 on 2024-03-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_space_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='activeProposals',
            new_name='active_proposals',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='memberCounts',
            new_name='member_counts',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='proposalCounts',
            new_name='proposal_counts',
        ),
    ]
