# Generated by Django 5.0.3 on 2024-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_rename_activeproposals_space_active_proposals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
