# Generated by Django 5.0.3 on 2024-03-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_rename_member_counts_space_members_counts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='members_counts',
            new_name='members_count',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='proposals_counts',
            new_name='proposals_count',
        ),
    ]
