# Generated by Django 5.0.3 on 2024-04-02 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_rename_members_counts_space_members_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceAppTreeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip', models.TextField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('command', models.JSONField(default=dict)),
                ('collapsible_state', models.IntegerField(default=0, null=True)),
                ('action', models.JSONField(default=dict)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_node_tree_node', to='space.spaceapptreenode')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_app_tree_node', to='space.space')),
            ],
        ),
    ]
